### ISSUE TITLE
Issue with Staking Requirements for Dual-Miners on SN32 Leading to Deregistration

### ISSUE THREAD

**Issue by creativeessence** [It-s-AI/llm-detection#43]
### **Description**
We are currently running dual-miners on SN32, but we face repeated deregistrations despite having high TRUST (0.96) and VTRUST (0.87) scores. The underlying issue seems to stem from the conflicting staking requirements for miners and validators on this subnet.

### **Issue Details**
To operate as a miner on SN32, the staking amount must be less than 4096.
However, to qualify as a validator, the staking amount must exceed 1024. This range forces dual-miners like us to adjust our stakes to fit within these limits, which significantly reduces our emissions. Consequently, this reduction in emissions has led to our deregistration despite maintaining high trust scores.

### **Suggested Resolution**
I propose commenting [this](https://github.com/It-s-AI/llm-detection/blob/main/detection/utils/uids.py#L24) out to let validators query other validators serving axons (aka. dual-miners)

**Comment by lnfin** [comment]
Thanks for bringing this up!

As subnet owners we strongly believe that validating and mining should be distinct roles. Neurons with dual roles lack competitive quality and don't enhance the strength of our network, as they are often dependent on additional emissions from both validator and miner activities to survive.

Our subnet operates in a competitive environment for both miners and validators. To be part of our subnet you need to either:

1. Increase the stake on your validator: This ensures you have significant influence over the weight distribution.
2. Improve the quality of your miner: A higher quality miner contributes more value to our subnet.

We find it unacceptable for participants to have only partial stakes or medium miner quality and attempt to combine them to qualify for emissions on our subnet.

This isn’t just our opinion — it’s a common practice across top-tier subnets like Text Prompting, Targon, Omega, and Omron. All of these subnets enforce a maximum stake threshold for miners.

**Comment by creativeessence** [comment]
> Thanks for bringing this up!
> 
> As subnet owners we strongly believe that validating and mining should be distinct roles. Neurons with dual roles lack competitive quality and don't enhance the strength of our network, as they are often dependent on additional emissions from both validator and miner activities to survive.
> 
> Our subnet operates in a competitive environment for both miners and validators. To be part of our subnet you need to either:
> 
> 1. Increase the stake on your validator: This ensures you have significant influence over the weight distribution.
> 2. Improve the quality of your miner: A higher quality miner contributes more value to our subnet.
> 
> We find it unacceptable for participants to have only partial stakes or medium miner quality and attempt to combine them to qualify for emissions on our subnet.
> 
> This isn’t just our opinion — it’s a common practice across top-tier subnets like Text Prompting, Targon, Omega, and Omron. All of these subnets enforce a maximum stake threshold for miners.

Dual-mining was your recommendation to stay registered on your subnet (SN32).
Let me confirm some things on my side and back to you.
